CREATE TABLE IF NOT EXISTS `examples`.`tweets` (
	  id CHAR(26) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	  user_uuid CHAR(26) NOT NULL,
	  content VARCHAR(256) NOT NULL,
  	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  	updated_at TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP ,
  	CONSTRAINT fk_tweets_required_users_uuid
  	FOREIGN KEY(user_uuid)
  	REFERENCES users(uuid)
  	ON DELETE RESTRICT
) ENGINE= InnoDB;
