CREATE TABLE IF NOT EXISTS `examples`.`users`(
    uuid CHAR(26) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    updated_at TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP ,
    PRIMARY KEY(uuid)
) ENGINE= InnoDB;
